### ISSUE TITLE
Unable to log into Bitwardon desktop app on PopOS with .local address

### ISSUE THREAD

**Issue by chadat23** [Start9Labs/vaultwarden-wrapper#13] opened 2022-01-27 20:04 UTC
### Prerequisites
- [x]  I have searched for existing issues that already report this problem, without success.

### EmbassyOS Version
bf7ceb6

### Device
Laptop/Desktop

### Device OS
Linux

### Device OS Version
PopOS 21.10

### Browser
NA

### Current Behavior
While trying to use the Bitwardon desktop app with the Server URL set to https:// ...address... .local, login attempts keep failing and the following error message keeps being generated: "An error has occurred. Failed to fetch". The same URL is however working with the Firefox plugin.

Anything else?
The same URL works in the Firefox Bitwardon extension. The same behavior was seen regardless of install method (.deb, flatpak via the Pop app manager, and appImage).

![image](https://user-images.githubusercontent.com/5481785/151434629-6c27d722-0153-401b-8646-01e201589ed1.png)

**Comment by ProofOfKeags** [comment] 2022-01-27 22:01
@kn0wmad since you self-assigned this, if you are taking it on I would attempt to start the desktop app from the CLI so you can capture stdout. It will likely show you exactly what the problem is. I suspect that the issue is related to how dns is resolved and whether mdns is taken into account.

**Comment by kn0wmad** [comment] 2022-01-27 22:04
> @kn0wmad since you self-assigned this, if you are taking it on I would attempt to start the desktop app from the CLI so you can capture stdout. It will likely show you exactly what the problem is. I suspect that the issue is related to how dns is resolved and whether mdns is taken into account.

I'm currently looking for testers for this as I cannot reproduce.  I was going to update after getting more information

**Comment by ProofOfKeags** [comment] 2022-01-27 22:13
> ...as I cannot reproduce.

So your bitwarden works fine over LAN?

**Comment by kn0wmad** [comment] 2022-01-27 23:58
> > ...as I cannot reproduce.
> 
> So your bitwarden works fine over LAN?

Correct

**Comment by lvlouro** [comment] 2022-01-28 21:43
Not sure if this is relevant but,
In ubuntu 20.04 LTS I get different errors if using snap or .deb/.appimage

snap app `ERR_NAME_NOT_RESOLVED`

.deb or .appimage `ERR_CERT_AUTHORITY_INVALID`

**Comment by lvlouro** [comment] 2022-01-28 21:50
Successfully connected .appimage to .onion by using
`./Bitwarden-1.30.0-x86_64.AppImage --proxy-server=socks5://127.0.0.1:9050`

**Comment by lvlouro** [comment] 2022-01-28 22:00
also works with
snap `snap run  bitwarden --proxy-server=socks5://127.0.0.1:9050`

and .deb
`bitwarden --proxy-server=socks5://127.0.0.1:9050`

**Comment by kn0wmad** [comment] 2022-01-29 00:13
Tor functionality with a proxy flag will work fine.  I'll get this documented, thank you for your service!

**Comment by ProofOfKeags** [comment] 2022-01-31 18:38
> .deb or .appimage ERR_CERT_AUTHORITY_INVALID

This is a result of you not having the CA installed all the way to your system most likely.

**Comment by kn0wmad** [comment] 2022-02-11 19:32
Closing this for now.  Directions for using Bitwarden desktop app using Tor have been added to 0.3 docs.  Release of those docs is imminent.  Feel free to comment with questions / concerns

**Closed by kn0wmad** 2022-02-11 19:32 UTC
Labels: Bug
